#!/usr/bin/env python3
import os
import subprocess

TEST_BIN = "./test"

# Compile the test binary if it does not exist
if not os.path.exists(TEST_BIN):
    subprocess.run(["g++", "./test.cpp", "-o", TEST_BIN], check=True)

# Run the test binary
subprocess.run([TEST_BIN], check=True)
