name: Pages

on:
  push:
    branches: [ "main" ]
    paths:
      - bob.hpp
      - docs/Doxyfile

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup C++
        uses: aminya/setup-cpp@v1

      - name: Install doxygen
        run: sudo apt install -y doxygen

      - name: Compile Bob
        run: g++ bob.cpp -o bob

      - name: Generate Site
        run: ./bob doc

      - name: Upload Documentation Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/html

  # Deploy job
  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
